name: "Send Slack Status Notification"
description: Slack Status Notification (replacement for circleci_slack_status orb).

inputs:
  message:
    description: The Markdown message contents
    required: true
  slack-webhook-url:
    description: Slack channel webhook URL to post the message
    required: true
  run-url:
    description: Self-referencing RUN
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Slack Notification
      uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844 # v1.23.0
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      with:
        payload: |
          {
            "message": "${{ inputs.message }}",
            "workflow_run": "${{ input.run-url }}"
          }