# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

{{- if (and (eq (.Values.runner.enabled | toString) "true") (eq (.Values.runner.odr.serviceAccount.create | toString) "true" )) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "waypoint.fullname" . }}-runner-odr-rolebinding-custom
  labels:
    app.kubernetes.io/name: {{ include "waypoint.name" . }}-runner
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: {{ template "waypoint.fullname" . }}-runner-odr
subjects:
  - kind: ServiceAccount
    name: {{ template "waypoint.runner.odr.serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
