# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

{{- if (and (eq (.Values.runner.enabled | toString) "true") (eq (.Values.runner.odr.serviceAccount.create | toString) "true" )) }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "waypoint.fullname" . }}-runner-odr
  labels:
    app.kubernetes.io/name: {{ include "waypoint.name" . }}-runner-odr
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
{{- end }}
