{{- if (and (eq (.Values.runner.enabled | toString) "true") (eq (.Values.runner.serviceAccount.create | toString) "true" )) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "waypoint.runner.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "waypoint.chart" . }}
    app.kubernetes.io/name: {{ include "waypoint.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{ template "waypoint.runner.serviceAccount.annotations" . }}
{{ end }}
