{{- if (and (eq (.Values.runner.enabled | toString) "true") (eq (.Values.runner.odr.serviceAccount.create | toString) "true" )) }}

{{/* If no managedNamespaces are provided, default to the release namespace */}}
{{ $managedNamespaces := list  }}
{{- range .Values.runner.odr.managedNamespaces }}
  {{ $managedNamespaces = append $managedNamespaces . }}
{{- end -}}
{{- if eq (len $managedNamespaces) 0 -}}
  {{ $managedNamespaces = append $managedNamespaces .Release.Namespace }}
{{- end -}}

{{- range $managedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "waypoint.fullname" $ }}-runner-odr-rolebinding-edit
  namespace: {{ . }}
  labels:
    app.kubernetes.io/name: {{ include "waypoint.name" $ }}-runner
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ template "waypoint.runner.odr.serviceAccount.name" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}

{{- end }}
