{{- if (eq (.Values.runner.enabled | toString) "true") }}
# StatefulSet to run the Waypoint static runner.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "waypoint.fullname" . }}-runner
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "waypoint.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- template "waypoint.statefulSet.annotations" . }}
spec:
  serviceName: {{ template "waypoint.fullname" . }}-runner
  replicas: {{ .Values.runner.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "waypoint.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: runner
  volumeClaimTemplates:
    - metadata:
        name: data-{{ .Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.runner.storage.size }}
        {{- if .Values.runner.storage.storageClass }}
        storageClassName: {{ .Values.runner.storage.storageClass }}
        {{- end }}
  template:
    metadata:
      labels:
        helm.sh/chart: {{ template "waypoint.chart" . }}
        app.kubernetes.io/name: {{ template "waypoint.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: runner
        {{- if  .Values.runner.extraLabels -}}
          {{- toYaml .Values.runner.extraLabels | nindent 8 -}}
        {{- end -}}
      {{ template "waypoint.annotations" . }}
    spec:
      {{- if .Values.runner.priorityClassName }}
      priorityClassName: {{ .Values.runner.priorityClassName }}
      {{- end }}
      serviceAccountName: {{ template "waypoint.runner.serviceAccount.name" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: home
          emptyDir: {}
      {{- if .Values.server.enabled }}
        - name: token
          secret:
            secretName: {{ template "waypoint.runnerTokenSecret" . }}
      {{- else if .Values.runner.server.tokenSecret }}
        - name: token
          secret:
            secretName: {{ .Values.runner.server.tokenSecret }}
      {{- end }}
      {{- include "imagePullSecrets" . | nindent 6 }}
      {{- if .Values.server.enabled }}
      initContainers:
      - name: wait-for-token
        image: "busybox"
        command:
        - /bin/sh
        - "-ec"
        - |
          until [ -s "/secret/token" ]; do
            echo "Waiting for runner token secret '/secret/token' to be populated from secret..."
            sleep 2
          done
        volumeMounts:
          - name: token
            mountPath: /secret
            readOnly: true
      {{- end }}
      containers:
        - name: waypoint
          resources:
{{ toYaml .Values.runner.resources | indent 12 }}
          image: {{ .Values.runner.image.repository }}:{{ .Values.runner.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.runner.image.pullPolicy }}
          command:
          - "waypoint"
          args:
          - "runner"
          - "agent"
          {{- if .Values.runner.id }}
          - "-id={{ .Values.runner.id }}"
          {{- end }}
          - "-liveness-tcp-addr=:1234"
          {{- if (and .Values.runner.server.addr .Values.runner.server.cookie) }}
          - "-cookie={{ .Values.runner.server.cookie }}"
          {{- end }}
          - "-state-dir=/data/runner"
          {{- range .Values.runner.agentArgs }}
          - "{{ . }}"
          {{- end }}
          env:
            - name: HOME
              value: /home/waypoint
            {{- if .Values.runner.server.addr }}
            - name: WAYPOINT_SERVER_ADDR
              value: {{ .Values.runner.server.addr }}
            - name: WAYPOINT_SERVER_TLS
              value: "{{ .Values.runner.server.tls | toString }}"
            - name: WAYPOINT_SERVER_TLS_SKIP_VERIFY
              value: "{{ .Values.runner.server.tlsSkipVerify | toString }}"
            {{- else }}
            - name: WAYPOINT_SERVER_ADDR
              value: {{ template "waypoint.fullname" . }}-server:9701
            - name: WAYPOINT_SERVER_TLS
              value: "true"
            - name: WAYPOINT_SERVER_TLS_SKIP_VERIFY
              value: "true"
            {{- end }}
            {{- if .Values.server.enabled }}
            - name: WAYPOINT_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ template "waypoint.runnerTokenSecret" . }}
                  key: token
            {{- else if .Values.runner.server.tokenSecret }}
            - name: WAYPOINT_SERVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.runner.server.tokenSecret }}
                  key: token
            {{- end }}
          volumeMounts:
            - name: home
              mountPath: /home/waypoint
            - name: data-{{ .Release.Namespace }}
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 1234
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
      {{- if .Values.runner.nodeSelector }}
      nodeSelector:
        {{ tpl .Values.runner.nodeSelector . | indent 8 | trim }}
      {{- end }}
{{ end }}
