{{- if (eq (.Values.server.enabled | toString) "true") }}
{{- $prev := (lookup "v1" "Secret" .Release.Namespace (include "waypoint.serverTokenSecret" . )) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "waypoint.serverTokenSecret" . }}
  labels:
    app.kubernetes.io/name: {{ include "waypoint.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if $prev }}
  token: {{ default "\"\"" (index $prev.data "token") }}
  {{- else }}
  token: ""
  {{- end }}

{{ end }}
